name: Test code and embed into README

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Ser up Python
      - name: Install dependency
      - name: Markdown
      - name: Check modified
      - name: Commit fies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-versions: '3.10'
      - name: Install dependency
        run: |
          pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: pytest test_src --junit-xml results/pytest.xml
        continue-on error: true
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results
          path: results/* .xml
      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      -name: Publish Unit Test Results
